server:
  port: ${PORT:8080}

cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}

krx:
  api:
    key: ${KRX_API_KEY:mykey}
    urls:
      kospi: https://data-dbg.krx.co.kr/svc/apis/idx/kospi_dd_trd
      krx: https://data-dbg.krx.co.kr/svc/apis/idx/krx_dd_trd
      stock: https://data-dbg.krx.co.kr/svc/apis/sto/ksq_bydd_trd
      konex: https://data-dbg.krx.co.kr/svc/apis/sto/knx_bydd_trd
      stk: https://data-dbg.krx.co.kr/svc/apis/sto/stk_bydd_trd

fsc:
  api:
    key: ${FSC_API_KEY:mykey}
    url: https://apis.data.go.kr/1160100/service/GetStockSecuritiesInfoService/getStockPriceInfo
